markdown:       kramdown
permalink:      /blog/:title.html
paginate:       5
paginate_path:  /blog/page:num
exclude:        [ external ]
highlighter:    pygments

kramdown:
        input: GFM

category_archive:
        path: /blog/category
